Yeji/week2
algorithm-cote-study/goormthon_challenge pull request #9
Opened 2023-08-22 01:50 UTC by cyeji

- week1 day5
이진수 정렬 (14분 27초)

- week2 day1
문자열 나누기 (46분 54초)

- week2 day2
구름 찾기 깃발 (14분 53초)

2023-08-22 10:34 UTC, songjuAhn approved these changes

2023-08-22 10:34 UTC, songjuAhn commented on src/main/java/com/goorm/week2/day1/yeji/Solution.java
> +        List<String> sortedUniqueSubStrings = arrayList.stream().distinct().sorted().toList();
중복을 제거하는 set 타입의 데이터형을 사용했으면 더 좋았을 것 같아요

2023-08-22 12:35 UTC, cyeji commented on src/main/java/com/goorm/week2/day1/yeji/Solution.java
> +        List<String> sortedUniqueSubStrings = arrayList.stream().distinct().sorted().toList();
배열에서 중복제거 후 정렬하였는데 TreeSet으로 변경했습니다 :)

2023-08-23 10:50 UTC, seunggulee1007 requested changes

2023-08-23 10:50 UTC, seunggulee1007 commented on src/main/java/com/goorm/week1/day5/yeji/Solution.java
> +    private static Integer sortedBinary(int[] input, int[] nums) {
int[] input 을 넘길 것 없이 비교하고자 하는 숫자만 넘겨주면 될 것 같네요

2023-08-23 10:50 UTC, seunggulee1007 commented on src/main/java/com/goorm/week1/day5/yeji/Solution.java
> +    private static Integer sortedBinary(int[] input, int[] nums) {
반환타입은 기본형이 더 좋습니다.
어차피 넘길 타입은 기본형인데 쓸데없는 오토 언박싱 일어납니다.

2023-08-23 10:50 UTC, seunggulee1007 commented on src/main/java/com/goorm/week2/day2/yeji/Solution.java
> +        List<Cloud> locations = new ArrayList<>();
타입은 Cloud인데 변수명은 locations네요. 일치시켜주는 것이 좋을 것 같습니다.

2023-08-24 03:44 UTC, cyeji commented on src/main/java/com/goorm/week1/day5/yeji/Solution.java
> +    private static Integer sortedBinary(int[] input, int[] nums) {
네 변경했습니다

2023-08-24 03:44 UTC, cyeji commented on src/main/java/com/goorm/week1/day5/yeji/Solution.java
> +    private static Integer sortedBinary(int[] input, int[] nums) {
변경했습니다

2023-08-24 03:44 UTC, cyeji commented on src/main/java/com/goorm/week2/day2/yeji/Solution.java
> +        List<Cloud> locations = new ArrayList<>();
변경했습니다

2023-08-24 11:36 UTC, seunggulee1007 approved these changes
고생하셨습니다:)

2023-08-24 11:59 UTC, merged